import friendimg from "../assets/friendsimg/friendimg.png";
export const INITIAL_DATA = {
  firstName: "",
  lastName: "",
  email: "",
  password: "",
  date: "",
  username: "",
  education: "",
  interests: "",
};
export const ORG_DATA = {
  name: "",
  typeOfWork: "",
  emailOrg: "",
  passwordOrg: "",
  dataContactPerson: "",
  jobPosition: "",
  usernameOrg: "",
  number: "",
  socialLinks: "",
  reason: "",
};

export const FRIENDS_DB = [
  {
    id: 1,
    img: friendimg,
    firstName: "Кутманшер",
    lastName: "Эрмеков",
    email: "kutman@example.com",
    password: "kutman123",
    date: "2001-04-15",
    username: "kutzhokg",
    education: "Kyrgyz State University of Informatics",
    interests: "web, book, pro, coding, cycling, running",
    desc: "Будущий data scientist. Люблю разбираться в числах, участвовать в хакатонах. Разрабатываю мобильные приложения, увлекаюсь баскетболом и организую мероприятия.",
  },
  {
    id: 2,
    img: friendimg,
    firstName: "Давлет",
    lastName: "Азимов",
    email: "davlet@example.com",
    password: "davlet123",
    date: "2000-09-23",
    username: "davletaz",
    education: "Bishkek Academy of Finance and Economics",
    interests: "coding, gaming, music, reading",
    desc: "Интересуюсь разработкой игр и веб-приложений. Участвую в хакатонах и занимаюсь бегом.",
  },
  {
    id: 3,
    img: friendimg,
    firstName: "Согдиана",
    lastName: "Токтогулова",
    email: "sogdiana@example.com",
    password: "sogdiana123",
    date: "2002-02-10",
    username: "sogdia",
    education: "American University of Central Asia",
    interests: "pro, art, music, photography, coding",
    desc: "Увлекаюсь искусством, фотографией и программированием. Учусь на data scientist и создаю креативные проекты.",
  },
];
